HelloWord/force-app/main/default/objects/Candidate_Atul__c/Candidate_Atul__c.object-meta.xml
<CustomObject>
    <label>Candidate_Atul</label>
    <nameField>
        <label>Candidate_AtulR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_Atuls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Job_Atul__c/Job_Atul__c.object-meta.xml
<CustomObject>
    <label>Job_Atul</label>
    <nameField>
        <label>Job_Atul</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Atuls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management        Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Expires_On__c.field-meta.xml
<CustomField>
    <fullName>Expires_On__c</fullName>
    <description>Expires_On</description>
    <label>Expires On</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Position</description>
    <label>Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>rr</fullName>
            </value>
            <value>
                <fullName>sadfs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Managemen</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Salary_Offered__c.field-meta.xml
<CustomField>
    <fullName>Salary_Offered__c</fullName>
    <label>Salary Offered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/classes/JobExtension.cls
public class JobExtension {
   
    public Job_Atul__c job {get; set;}  
    public Candidate_Atul__c candidate {get; set;}
    public List<Job_Atul__c> createdJob {get; set;}
    public list<Job_Atul__c> lstOfActivatejob{get;set;}
    
    public JobExtension(ApexPages.StandardController controller)  
    {
        string jobId = Apexpages.currentPage().getParameters().get('jobId');
        if(!String.isBlank(jobId))
        {
            createdJob = [SELECT Name,Expires_On__c,Positions__c,Qualification_Required__c,Certification_Required__c,Required_Skills__c,Salary_Offered__c FROM Job_Atul__c WHERE Id=:jobId];
        	job = createdJob[0];
          
        }
        else        
            this.job = (Job_Atul__c)controller.getRecord(); 
    }    
    public PageReference saveNext()
    {
        PageReference pageRef;
        if(job != NULL){
            if(job.Id != NULL)
            {
               update job;
               pageRef = Page.JobDisplayPage;
            }
            else
            {
                insert job; 
                pageRef = Page.RegistrationPage2;               
            }  
             pageref.getParameters().put('jobId', job.Id);
        } 
        pageRef.setRedirect(true);
        return pageRef;
    }
    public PageReference goToJobPortal()
    {
            PageReference pageRef;
            string jobId = Apexpages.currentPage().getParameters().get('jobId');
            createdJob=[SELECT Active__c FROM Job_Atul__c WHERE Id=:jobId];
            system.debug('active'+createdJob);
            if(createdJob[0].Active__c==false)
            {
              createdJob[0].Active__c=True;
              update createdJob;
             
              pageRef = Page.JobPortalPage;
              //pageref.getParameters().put('jobId', job.Id);
              pageRef.setRedirect(true);
              return pageRef;
           }
          else
          {
             return null;
          }
     }
   
    
}