HelloWord/force-app/main/default/objects/Candidate_Atul__c/Candidate_Atul__c.object-meta.xml
<CustomObject>
    <label>Candidate_Atul</label>
    <nameField>
        <label>Candidate_AtulR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_Atuls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job_Atul</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Job_Atul__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Job_Atul__c</referenceTo>
    <relationshipLabel>Candidate_Atuls</relationshipLabel>
    <relationshipName>Candidate_Atuls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
                <default>true</default>
                <label>Applied</label>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/Job_Atul__c.object-meta.xml
<CustomObject>
    <label>Job_Atul</label>
    <nameField>
        <label>Job_Atul</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Atuls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Position</description>
    <label>Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/classes/CandidateTriggerHandler.cls
public class CandidateTriggerHandler {
    
      
    /* public static void OnDecativeJobForAppliedCandidate(List<Candidate_Atul__c> lstNewCandidate)
     {
          
       
         Integer HiredCandidate=0;
        List<Job_Atul__c>  lstofjob =new List<Job_Atul__c>();
        Job_Atul__c objjobs=new Job_Atul__c();
      
        lstofjob = [SELECT Active__c,Positions__c FROM Job_Atul__c WHERE ID =:lstNewCandidate[0].Job__c];
       
        for(Candidate_Atul__c objCandidate:lstNewCandidate)
        {
            if(lstNewCandidate[0].Status__c=='Hired')
           {
            HiredCandidate++;
           }
        }
        

        if(lstofjob[0].Active__c==True )
        {
             system.debug('Hired Candidate'+HiredCandidate);
            if(HiredCandidate==lstofjob[0].Positions__c)
            {
               
                  lstofjob[0].Active__c=False;
                  update lstofjob;
            }
            else 
            {
                 
               lstNewCandidate[0].Status__c.addError('Candidates can not apply for it anymore.');
            }
            
        }
        else
        {
            lstNewCandidate[0].Status__c.addError('Job is decative.');
        }

   }*/
     public static void OnNotAllowCandidateForDeactiveJob(List<Candidate_Atul__c> lstNewCandidate1)
     {
            integer counter=0;
            system.debug('new candidate list'+lstNewCandidate1);
            List<Candidate_Atul__c> lstHiredcandidate=[SELECT Id FROM Candidate_Atul__c WHERE Status__c = : 'Hired'];
         //  List<Candidate_Atul__c> lstAppliedcandidate=[SELECT Id FROM Candidate_Atul__c WHERE Status__c = : 'Applied'];
             Candidate_Atul__c objcan=new Candidate_Atul__c();
            Job_Atul__c objJobDetail = [SELECT Active__c,Positions__c FROM Job_Atul__c WHERE ID =:lstNewCandidate1[0].Job__c];
            system.debug('job detail'+objJobDetail);
           
            System.debug('list of candidate hired'+lstHiredcandidate.size());
            
                     if(objJobDetail.Active__c==True)
                     {
                                
                                if(lstHiredcandidate.size()==objJobDetail.Positions__c)
                                {
                                     system.debug('conditaion block');
                                     objcan.Status__c.AddError('Sorry, No vacancies available for this Job');
                                }
                                else
                                {
                                    
                                }
                               
                     }
    }
    
   
}