HelloWord/force-app/main/default/objects/Candidate_Atul__c/Candidate_Atul__c.object-meta.xml
<CustomObject>
    <label>Candidate_Atul</label>
    <nameField>
        <label>Candidate_AtulR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_Atuls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>aa</description>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job_Atul</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Job_Atul__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Job_Atul__c</referenceTo>
    <relationshipLabel>Candidate_Atuls</relationshipLabel>
    <relationshipName>Candidate_Atuls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
                <color>#CC33CC</color>
                <default>true</default>
                <label>Mr</label>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Candidate_Atul__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
                <default>true</default>
                <label>Applied</label>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/Job_Atul__c.object-meta.xml
<CustomObject>
    <label>Job_Atul</label>
    <nameField>
        <label>Job_Atul</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_Atuls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management        Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Expires_On__c.field-meta.xml
<CustomField>
    <fullName>Expires_On__c</fullName>
    <description>Expires_On</description>
    <label>Expires On</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Positions__c.field-meta.xml
<CustomField>
    <fullName>Positions__c</fullName>
    <description>Position</description>
    <label>Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>rr</fullName>
            </value>
            <value>
                <fullName>sadfs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Managemen</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HelloWord/force-app/main/default/objects/Job_Atul__c/fields/Salary_Offered__c.field-meta.xml
<CustomField>
    <fullName>Salary_Offered__c</fullName>
    <label>Salary Offered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HelloWord/force-app/main/default/classes/JobPortalManager.cls
public class JobPortalManager {
    
    public Candidate_Atul__c objcandidate {get;set;}
    public list<Candidate_Atul__c> lstcandidate{get;set;}
    public list<Job_Atul__c> lstOfActivatejob{get;set;}
    Public Attachment myfile{get;set;}
   
    public JobPortalManager()
    {
          objcandidate=new Candidate_Atul__c();
           myfile = new Attachment();
          system.debug('lstOfActivatejob'+lstOfActivatejob); 
          string jobId = Apexpages.currentPage().getParameters().get('jobId');
          System.debug('con job id::'+jobId);
          lstOfActivatejob=[SELECT Name,Expires_On__c,Positions__c,Qualification_Required__c,Certification_Required__c,Required_Skills__c,Salary_Offered__c FROM Job_Atul__c WHERE Active__c=:True LIMIT 5];
          lstcandidate=[SELECT Name,Last_Name__c,Salutation__c,Expected_Salary__c,Job__c,Status__c FROM Candidate_Atul__c ];
    } 
    public PageReference applyJobForCandidate()
    {
          
          PageReference pageRef;  
          string jobId = Apexpages.currentPage().getParameters().get('jobId');
        
          pageRef = Page.CandidateRegistrationPage; 
          pageref.getParameters().put('jobId', jobId);
          pageRef.setRedirect(true);
          return pageRef;
    }
    Public Attachment getmyfile()
    {
        return myfile;
    }
    public PageReference saveCandidateDetail()
    {
          PageReference pageRef;  
          string jobId = Apexpages.currentPage().getParameters().get('jobId');
          objcandidate.Job__c=jobId;
          insert objcandidate;
         // Attachment a = new Attachment(parentId = objcandidate.Id, name=myfile.name, body = myfile.body);
        //  insert a;
          pageRef = Page.CandidateJobDispaly; 
          pageRef.setRedirect(true);
          return pageRef;
      }

}